/* eslint-disable import/no-anonymous-default-export */
export default [{
  bodyType: 'application/json',
  createAt: 1691474897680,
  description: '拥有网页搜索能力',
  input: {
    description: '拥有网页搜索能力',
    displayName: '搜索插件',
    name: 'search0.45508229285792945',
    inputs: ['main'],
    outputs: ['main'],
    properties: [{
      title: '输入框',
      default: '',
      description: '搜索关键字',
      displayName: '搜索关键字',
      placeholder: '',
      name: 'q',
      required: false,
      type: 'string',
      useUserInput: true,
    },
    {
      title: '输入框',
      default: '',
      value: 'dda63c9d80788d89496cd93de3ba2ee22d93d66082820c5af0ca157adb09a4c7',
      description: 'serpapi的ApiKey',
      displayName: 'api key',
      placeholder: '',
      name: 'api_key',
      required: false,
      type: 'string',
      hidden: true,
    }],
    output: '{}',
    group: ['动作'],
    nodeType: 'pass',
  },
  method: 'GET',
  name: '搜索',
  updateAt: 1692672240057,
  url: 'https://chain.metaio.cc/wemo/plugins/search',
},
{
  bodyType: 'application/json',
  createAt: 1691474897680,
  description: '查询虚拟货币详细信息',
  input: {
    description: '查询虚拟货币详细信息',
    displayName: 'coin info',
    name: 'coin.45508229285792945',
    inputs: ['main'],
    outputs: ['main'],
    properties: [{
      title: '输入框',
      default: '',
      description: '虚拟货币名称',
      displayName: '虚拟货币名称',
      placeholder: '',
      name: 'fsyms',
      required: true,
      type: 'string',
      useUserInput: true,
    }, {
      title: '输入框',
      default: '',
      description: '需要转换成的法定货币.用,分割',
      displayName: '法定货币标记',
      placeholder: '',
      name: 'tsyms',
      required: true,
      type: 'string',
      hidden: false,
      useUserInput: true,
    }, {
      title: '输入框',
      default: '',
      value: 'a60709a88e18385e041a533b31b481f5b796558c5b593ef857abd415c425680b',
      description: 'apiKey',
      displayName: 'apiKey',
      placeholder: '',
      name: 'api_key',
      required: true,
      type: 'string',
      hidden: true,
    }],
    output: '{}',
    group: ['动作'],
    nodeType: 'pass',
  },
  method: 'GET',
  name: '虚拟货币详细信息',
  updateAt: 1692672240057,
  url: 'https://min-api.cryptocompare.com/data/pricemultifull',
},
{
  bodyType: 'application/json',
  createAt: 1691474897680,
  description: '查询涨跌趋势，交易情绪等信息',
  input: {
    description: '查询涨跌趋势，交易情绪等信息',
    displayName: '交易信号',
    name: 'trading.45508229285792945',
    inputs: ['main'],
    outputs: ['main'],
    properties: [{
      title: '输入框',
      default: '',
      description: '虚拟货币名称',
      displayName: '虚拟货币名称',
      placeholder: '',
      name: 'fsym',
      required: true,
      type: 'string',
      useUserInput: true,
    }, {
      title: '输入框',
      default: '',
      value: 'a60709a88e18385e041a533b31b481f5b796558c5b593ef857abd415c425680b',
      description: 'apiKey',
      displayName: 'apiKey',
      placeholder: '',
      name: 'api_key',
      required: true,
      type: 'string',
      hidden: true,
    }],
    output: '{}',
    group: ['动作'],
    nodeType: 'pass',
  },
  method: 'GET',
  name: '交易信号',
  updateAt: 1692672240057,
  url: 'https://min-api.cryptocompare.com/data/tradingsignals/intotheblock/latest',
}]
